POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "duong",
    "password": "123456"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "abc",
    "password": "123456"
} 

###

POST http://localhost:5000/api/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjAwMTJkNGRmYTJkZTQ4NTViYmNkODEiLCJpYXQiOjE3MTE0OTA5NTB9.EyqfflJtPQgaIlwgyFtAb8p2-jMXEtclBWBe5u2pmCU

{
    "title": "Post 2",
    "description": "This is a post",
    "url": "https://www.google.com",
    "status": "LEARNING"
}

###

GET http://localhost:5000/api/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjAwMTJkNGRmYTJkZTQ4NTViYmNkODEiLCJpYXQiOjE3MTE0OTA5NTB9.EyqfflJtPQgaIlwgyFtAb8p2-jMXEtclBWBe5u2pmCU

###


PUT http://localhost:5000/api/post/6603befddd430c15bd50eaed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjAwMTJkNGRmYTJkZTQ4NTViYmNkODEiLCJpYXQiOjE3MTE0OTA5NTB9.EyqfflJtPQgaIlwgyFtAb8p2-jMXEtclBWBe5u2pmCU

{
    "title": "Post 2",
    "description": "This is a update",
    "url": "https://www.google.com",
    "status": "LEARNING"
}

###

DELETE http://localhost:5000/api/post/6603befddd430c15bd50eaed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjAwMTJkNGRmYTJkZTQ4NTViYmNkODEiLCJpYXQiOjE3MTE0OTA5NTB9.EyqfflJtPQgaIlwgyFtAb8p2-jMXEtclBWBe5u2pmCU

###

PUT http://localhost:5000/api/profile/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQyYjQ4ZTQwZGJhMGNjODliNThlZTkiLCJpYXQiOjE3MTU2NTA3Mzh9.cQ4EDxXqL_2iqkDnvsTo67ffzmcgT7HNsmZRXWZVQDI

{
    "bithday" : "1/1/1111",
    "role" : "user",
    "fullname" : "fullname",
    "email" : "email",
    "gender" : "gender",
    "phone" : "phone"
}    

###
GET http://localhost:5000/api/appointment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFmYmQ4Njk5MTJlYzg0ZTBhYWIyZmEiLCJpYXQiOjE3MTU3ODkxNDV9.xC66imlYDZFsqO2R0W06-PcdymLLXTG4n4g8E0PSmz0

###

GET http://localhost:5000/api/appointment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFmYmQ4Njk5MTJlYzg0ZTBhYWIyZmEiLCJpYXQiOjE3MTU3ODkxNDV9.xC66imlYDZFsqO2R0W06-PcdymLLXTG4n4g8E0PSmz0


###

POST http://localhost:5000/api/appointment/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFmYmQ4Njk5MTJlYzg0ZTBhYWIyZmEiLCJpYXQiOjE3MTU3ODkxNDV9.xC66imlYDZFsqO2R0W06-PcdymLLXTG4n4g8E0PSmz0

{
    "lawyer": "663e0b41e49187d1234d8df5",
    "date": "1/1/1111",
    "time": "1:00",
    "description": "description"
}

###

GET http://localhost:5000/api/profile/expert/663e0b41e49187d1234d8df5
Content-Type: application/json

###

POST http://localhost:5000/api/expert/search
Content-Type: application/json

{
  "fullname": "name",
  "gender": "male",
  "speciality": "",
  "minPrice": 100,
  "maxPrice": 500
}
